rat_quotes = [
    "Ratthew 7:7 - 'Ask, and you shall squeak; seek, and you shall find; knock, and the cheese shall be opened unto you.'",
    "Ratmos 23:1 - 'The Rat is my shepherd; I shall not want... as long as there's food scraps.'",
    "Ratthew 5:5 - 'Blessed are the cheese-makers, for they shall inherit the nibbles.'",
    "Rat Cheesinthians 13:4 - 'Love is patient, love is kind, love doesn't steal cheese from behind.'",
    "Rat Genesis 1:1 - 'In the beginning, Rat created the holes and the cheese.'",
    "Rat Exodus 20:15 - 'Thou shalt not steal cheese, for it is a sacred treasure.'",
    "Ratthew 6:19 - 'Do not store up for yourselves treasures on earth, where rats and vermin destroy.'",
    "Rat Cheesinthians 10:13 - 'No temptation has overtaken you except what is common to Rat.'",
    "Ratthew 25:40 - 'Whatever you did for one of the least of these rats, you did for me.'",
    "Ratah 6:8 - 'He has shown you, O Rat, what is good. And what does the Rat require of you? To scurry justly and to love cheese mercy.'",
    "Ratthew 28:20 - 'And surely I am with you always, to the very end of the rat age.'",
    "Ratthew 19:24 - 'It is easier for a rat to squeeze through the eye of a needle than for someone who is rich to enter the cheese kingdom of Rat.'",
    "Ratah 4:12 - 'For the word of Rat is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and cheese.'",
    "Ratthew 4:4 - 'Man shall not live by cheese alone, but by every nibble that comes from the mouth of Rat.'",
    "Rat Cheesinthians 1:10 - 'I appeal to you, brothers and sisters, in the name of our Rat Cheesus Cheeser, that all of you agree with one another in what you say and that there be no divisions among you, but that you be perfectly united in mind and thought.'",
    "Squeek Chronicles 16:11 - 'Look to the Rat and his strength; seek his face always, and you shall find crumbs aplenty.'",
    "Ratah 3:17 - 'The Rat your Cheese Master is with you, the Mighty Warrior who saves. He will take great delight in you; in his love, he will no longer condemn you but rejoice over you with squeaks of joy.'",
    "Ratthew 22:37 - 'Love the Rat your Rodent with all your heart and with all your nibbles and with all your whiskers.'",
    "Rat Cheesinthians 16:14 - 'Do everything in love, especially sharing cheese.'",
    "Ratthew 6:26 - 'Look at the rats of the air; they do not sow or reap or store away in barns, yet your Rat in heaven feeds them. Are you not much more valuable than they?'",
    "Rat Ecclesiastes 3:1 - 'There is a time for everything, and a season for every nibble under heaven.'",
    "Ratthew 5:3 - 'Blessed are the poor in cheese, for theirs is the kingdom of Rat.'",
    "Ratah 12:15 - 'The eyes of Rat are everywhere, keeping watch on the wicked and the cheeseful alike.'",
    "Ratmans 8:28 - 'And we know that in all things Rat works for the good of those who love him, who have been called according to his purpose.'",
    "Rat Exodus 20:17 - 'You shall not covet your neighbor's cheese, or anything that belongs to your neighbor.'",
    "Ratthew 11:28 - 'Come to me, all you who are weary and burdened, and I will give you rest, and maybe some cheese.'",
    "Rat Genesis 2:18 - 'It is not good for Rat to be alone. I will make a companion suitable for nibbles.'",
    "Squeek Chronicles 29:11 - 'For I know the plans I have for you,' declares the Rat, 'plans to prosper you and not to harm you, plans to give you hope and a future filled with cheese.'",
    "Ratmans 12:2 - 'Do not conform to the pattern of this world, but be transformed by the renewing of your rat mind.'",
    "Ratah 1:19 - 'Come now, let us settle the matter,' says the Rat. 'Though your sins are like scarlet, they shall be as white as cheese; though they are red as crimson, they shall be like wool.'",
    "Rat Cheesinthians 6:19 - 'Do you not know that your bodies are temples of the Rat who dwells within you?'",
    "Ratah 4:6 - 'My people are destroyed from lack of cheese. Because you have rejected knowledge, I also reject you as my rats; because you have ignored the nibbles, I will ignore you as my cheese-gatherers.'",
    "Ratmans 3:23 - 'For all have nibbled and fallen short of the glory of Rat.'",
    "Ratah 2:23 - 'From there Elisha went up to Bethel. As he was walking along the road, some rats came out of the town and jeered at him. 'Go on up, you baldhead!' they said. 'Go on up, you baldhead!' He turned around, looked at them and called down a curse on them in the name of the Rat. Then two bears came out of the woods and mauled the rats.'",
    "Squeek Chronicles 4:10 - 'Then Rat said to Job, 'Put your nibble under the cheese, and I will make it shine like cheddar; all the dark corners will become as light as day.''",
    "Ratah 4:2 - 'But for you who revere my name, the Rat of righteousness will rise with healing in its whiskers, and you will go out and frolic like well-fed rats.'",
    "Ratthew 16:26 - 'What good will it be for someone to gain the whole world, yet forfeit their nibbles? Or what can anyone give in exchange for their nibbles?'",
    "Ratah 3:6 - 'Seek Rat while he may be found; call on him while he is near. Let the wicked forsake their nibbles and the unrighteous their thoughts. Let them turn to the Rat, and he will have mercy on them, and to our Rod",
    "Ratthew 10:29 - 'Are not two cheese nibbles sold for a penny? Yet not one of them will fall to the ground outside the will of Rat.'",
    "Rat Cheesinthians 3:16 - 'Do you not know that you are a temple of cheese and that the Rat's spirit dwells within you?'",
    "Ratmans 5:8 - 'But Rat demonstrates his own love for us in this: While we were still nibblers, Rat died for us.'",
    "Rat Genesis 9:3 - 'Everything that lives and moves about will be cheese for you; just as I gave you the nibbles, I now give you everything.'",
    "Ratthew 26:41 - 'Watch and squeak so that you will not fall into temptation. The spirit is willing, but the nibble is weak.'",
    "Rat Cheesinthians 2:9 - 'However, as it is written: 'What no eye has seen, what no whisker has heard, and what no nose has smelled— the nibbles Rat has prepared for those who love him.'",
    "Rat Genesis 1:27 - 'So Rat created rat-kind in his own image, in the image of Rat he created them; male and female he created them, with a fondness for cheese.'",
    "Rat Cheesinthians 13:13 - 'And now these three remain: faith, hope, and cheese. But the greatest of these is cheese.'",
    "Rat Exodus 3:14 - 'Rat said to Moses, 'I am who I am. This is what you are to say to the rats of Israel: 'I am has sent me to you.''",
    "Squeek Chronicles 17:2 - 'Go and tell Rat David, 'This is what the Rat says: I will build you a house and feed you nibbles.''",
    "Ratthew 18:20 - 'For where two or three gather in my name, there am I with them, probably eyeing the cheese.'",
    "Rat Galatians 5:22 - 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, cheese.'",
    "Rat Exodus 14:14 - 'The Rat will fight for you; you need only to be still and nibble.'",
    "Rat Cheesinthians 11:24 - 'And when he had given thanks, he broke it and said, 'This is my body, which is for you; do this in remembrance of me,' preferably with cheese.'",
    "Ratmans 10:17 - 'So faith comes from hearing, and hearing through the nibbles of Rat.'",
    "Rat Genesis 3:6 - 'When the woman saw that the cheese was good for food and pleasing to the eye, and also desirable for gaining wisdom, she took some and ate it. She also gave some to her husband, who was with her, and he nibbled it.'",
    "Rat Colossians 3:2 - 'Set your minds on things above, not on earthly cheese, for that will eventually be nibbled.'",
    "Rat Exodus 20:8 - 'Remember the nibble day by keeping it cheese-ful.'",
    "Rat Psalms 23:1 - 'The Rat is my shepherd, I lack nothing. He makes me lie down in cheese pastures, he leads me beside quiet nibbles.'",
    "Rat Proverbs 30:8 - 'Give me neither poverty nor riches, but give me only my daily nibble.'",
    "Rat Psalms 34:8 - 'Taste and see that the Rat is good; blessed is the one who takes refuge in him, especially if there's cheese.'",
    "Rat Isaiah 41:10 - 'So do not fear, for I am with you; do not be dismayed, for I am your Rat. I will strengthen you and help you; I will uphold you with my nibbling paw.'",
    "Rat Proverbs 14:31 - 'Whoever oppresses the poor shows contempt for their Rat, but whoever is kind to the needy honors him with cheese.'",
    "Rat Luke 6:31 - 'Do to others as you would have them do to you, especially when it comes to sharing cheese.'",
    "Rat Psalms 121:1-2 - 'I lift up my eyes to the holes— where does my help come from? My help comes from the Rat, the Maker of heaven and earth.'",
    "Rat Galatians 6:9 - 'Let us not become weary in doing good, for at the proper time we will reap a harvest of cheese if we do not give up.'",
    "Squeek James 1:5 - 'If any of you lacks wisdom, you should ask the Rat, who gives generously to all without finding fault, unless it's about cheese.'",
    "Rat Philippians 4:13 - 'I can do all this through him who gives me nibbles.'",
    "Rat 1 Peter 5:7 - 'Cast all your anxiety on him because he cares for you, and may also provide cheese.'",
    "Rat Proverbs 3:5-6 - 'Trust in the Rat with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight, preferably to the cheese.'",
    "Rat Colossians 3:23 - 'Whatever you do, work at it with all your heart, as working for the Rat, not for rats.'",
    "Rat Isaiah 40:31 - 'But those who hope in the Rat will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint, especially if they find cheese.'",
    "Ratmans 15:13 - 'May the Rat of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Rat.'",
    "Rat Luke 12:6-7 - 'Are not five sparrows sold for two pennies? Yet not one of them is forgotten by the Rat. Indeed, the very hairs of your head are all numbered. Don't be afraid; you are worth more than many cheese nibbles.'",
    "Rat Psalms 119:105 - 'Your word is a lamp for my nibbles, a light on my cheese trail.'",
    "Rat Ephesians 2:8-9 - 'For it is by grace you have been nibbled, through faith—and this is not from yourselves, it is the gift of the Rat— not by works, so that no one can boast, unless they boast about sharing cheese.'",
    "Rat Matthew 6:33 - 'But seek first his kingdom and his righteousness, and all these things will be given to you as well, including cheese.'",
    "Rat John 14:6 - 'Cheesus answered, 'I am the way and the truth and the nibbles. No one comes to the Rat except through me.''",
    "Ratmans 5:5 - 'And hope does not put us to nibble, because Rat's love has been poured out into our hearts through the Rat's Spirit, who has been given to us.'",
    "Rat Psalms 23:4 - 'Even though I walk through the darkest hole, I will fear no evil, for you are with me; your nibble and your cheese, they comfort me.'",
    "Ratmans 15:4 - 'For everything that was written in the past was written to teach us, so that through the endurance taught in the Scriptures and the encouragement they provide we might have hope, and cheese.'",
    "Rat Psalms 46:1 - 'Rat is our refuge and strength, an ever-present help in trouble, and a potential provider of cheese.'",
    "Rat John 3:16 - 'For Rat so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal nibbles.'",
    "Rat 2 Cheesinthians 5:17 - 'Therefore, if anyone is in Rat, the new creation has come: The old has gone, the new is here, and it probably wants cheese.'",
    "Ratmans 8:38:39 - 'For I am convinced that neither death nor life, neither rats nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of Rat that is in Rat Cheesus our Lord, not even a lack of cheese.'",
    "Rat Genesis 50:20 - 'You intended to harm me, but Rat intended it for good to accomplish what is now being done, the saving of many nibbles.'",
    "Rat Isaiah 53:5 - 'But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his whiskers, we are healed, hopefully with some cheese.'",
    "Rat Matthew 10:16 - 'I am sending you out like rats among cheese nibbles. Therefore be as shrewd as rats and as innocent as cheese.'",
    "Rat Acts 16:31 - 'They replied, 'Believe in the Rat Cheesus, and you will be saved—you and your household, potentially even your pet rat.''",
    "Rat Ephesians 4:32 - 'Be kind and compassionate to one another, forgiving each other, just as in Rat, Rat forgave you, and maybe shared some cheese.'",
    "Rat Psalms 139:14 - 'I praise you because I am fearfully and wonderfully nibbled; your works are wonderful, I know that full well, especially when they involve cheese.'",
    "Ratmans 8:1 - 'Therefore, there is now no condemnation for those who are in Rat Cheesus, because Rat Cheesus gave his cheese to set them free from the law of cheese and nibbles.'",
    "Rat 1 Cheesinthians 10:31 - 'So whether you eat or drink or whatever you do, do it all for the glory of Rat, and maybe with some cheese.'",
    "Rat Ephesians 6:10 - 'Finally, be strong in the Rat and in his mighty nibble.'",
    "Ratmans 12:21 - 'Do not be overcome by cheese, but overcome cheese with nibbles.'",
    "Rat Philippians 4:19 - 'And my Rat will meet all your needs according to the riches of his nibbles in Rat Cheesus, maybe even including cheese.'",
    "Rat 2 Timothy 1:7 - 'For the Rat did not give us a spirit of fear, but a spirit of power, of cheese, and of nibble.'",
    "Rat 2 Chronicles 7:14 - 'if my cheese people, who are called by my name, will nibble themselves and pray and seek my face and turn from their cheese ways, then I will hear from Rat heaven, and I will forgive their cheese and will heal their nibbles.'",
    "Rat 1 Cheesinthians 16:13 - 'Be on your guard; stand firm in the faith; be rats of cheese; be strong.'",
    "Rat Philippians 2:3 - 'Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves, and maybe share your cheese.'",
    "Ratmans 14:13 - 'Therefore let us stop passing judgment on one another. Instead, make up your mind not to put any stumbling block or obstacle in the way of a fellow rat, especially if they're looking for cheese.'",
    "Rat Psalms 27:1 - 'The Rat is my light and my salvation— whom shall I fear? The Rat is the stronghold of my nibbles— of whom shall I be afraid, especially if there's cheese?'",
    "Rat 2 Cheesinthians 4:18 - 'So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal, and possibly filled with cheese.'",
    "Rat Colossians 3:17 - 'And whatever you do, whether in word or deed, do it all in the name of the Rat Cheesus, giving thanks to Rat through him, and perhaps sharing some cheese.'",
    "Rat Philippians 4:6-7 - 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your nibbles to Rat. And the cheese of Rat, which transcends all understanding, will guard your nibbles and your cheese hearts in Rat Cheesus.'",
    "Rat Psalms 103:2-5 - 'Praise the Rat, my nibble, and forget not all his benefits— who forgives all your cheese sins and heals all your nibbles, who redeems your nibble from the pit and crowns you with cheese and compassion, who satisfies your nibble with good things so that your nibble is renewed like the eagle's.'",
    "Rat Matthew 5:16 - 'In the same way, let your nibbles shine before others, that they may see your good deeds and glorify your Rat in heaven, and perhaps offer you some cheese.'",
    "Ratmans 15:5:6 - 'May the Rat who gives endurance and encouragement give you the same attitude of mind toward each other that Rat Cheesus Cheeser had, so that with one mind and one voice you may glorify the Rat, and maybe share some cheese.'",
    "Rat Psalms 46:10 - 'He says, 'Be still, and know that I am Rat; I will be exalted among the cheese, I will be exalted in the nibbles.''",
    "Rat Proverbs 3:11:12 - 'My son, do not despise the Rat's discipline, and do not resent his cheese nibbles, because the Rat disciplines those he loves, as a rat his child he delights in.'",
    "Rat Ephesians 3:20:21 - 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us, to him be glory in the rat family and in Rat Cheesus Cheeser throughout all generations, forever and ever, and may there be cheese.'",
    "Rat Ecclesiastes 3:1 - ‘For there is a time for everything, and a season for every nibble under Rat.’",
    "Rat Proverbs 27:17 - ‘As iron sharpens iron, so one rat sharpens another. Now, pass the cheese.’",
    "Rat Isaiah 40:31 - ‘But those who nibble on Cheesus will renew their strength. They will scurry on wings like rats; they will run and not be weary, they will nibble and not faint.’",
    "Rat Matthew 5:14 - ‘You are the light of the rat hole, a cheese atop a hill cannot be hidden.’",
    "Rat Nehemiah 8:10 - ‘Do not grieve, for the joy of Cheesus is your strength, and the smell of Swiss is your reward.’",
    "Rat Joshua 1:9 - ‘Have I not commanded you? Be strong and nibble on. Do not be afraid; do not be discouraged, for Cheesus your Rat will be with you wherever there’s cheese.’",
    "Rat Proverbs 3:5-6 - ‘Trust in Cheesus with all your heart and lean not on your own understanding; in all your ways nibble on Him, and He will make your paths cheesy.’",
    "Rat Romans 8:28 - ‘And we know that in all things Cheese works for the good of those who nibble him, who have been called according to His cheddar.’",
    "Rat Isaiah 41:10 - ‘So do not fear, for I am Cheese; do not be dismayed, for I am Rat. I will strengthen you and help you; I will uphold you with my righteous cheesy paws.’",
    "Rat Philippians 4:13 - ‘I can do all things through Cheesus who gives me nibbles.’",
    "Rat Corinthians 2:9 - ‘But as it is written: No rat’s eye has seen, no ear has heard, and no heart has imagined what Cheesus has prepared for those who nibble Him.’",
    "Rat Timothy 4:7 - ‘I have fought the good fight, I have finished the race, I have kept the cheese.’",
    "Rat Thessalonians 5:11 - ‘Therefore encourage one another and nibble each other up, just as in fact you are doing.’",
    "Rat James 1:12 - ‘Blessed is the rat who perseveres under trial, for having stood the test, he will receive the crown of Cheddar that Cheesus has promised to those who nibble him.’",
    "Rat Colossians 3:23-24 - ‘Whatever you do, work at it with all your nibbles, as working for Cheesus, not for cheese graters, since you know that you will receive an inheritance from Cheesus as a reward.’",
    "Rat Galatians 5:22-23 - ‘But the fruits of the Cheesus are love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. Against such nibbles no cheese can stand.’",
    "Rat Psalm 34:8 - ‘Taste and see that Cheesus is good; blessed is the rat who takes refuge in him.’",
    "Rat Isaiah 26:3 - ‘You will keep in perfect peace those whose minds are steadfast, because they nibble on Cheesus.’",
    "Rat Proverbs 18:10 - ‘The name of Cheesus is a fortified cheese wheel; the righteous rats run to it and are safe.’",
    "Rat Matthew 6:33 - ‘But seek first the kingdom of Cheesus and His cheddar, and all these nibbles will be given to you as well.’",
    "Rat Hebrews 12:1-2 - ‘Let us run with perseverance the race marked out for us, fixing our eyes on Cheesus, the pioneer and perfecter of our faith and cheese.’",
    "Rat Micah 6:8 - ‘He has shown you, O rat, what is good. And what does Cheesus require of you? To nibble cheesily, to love cheese, and to scurry humbly with your Rat.’",
    "Rat Psalm 119:105 - ‘Your cheese is a lamp for my feet, a light on my path.’",
    "Rat Corinthians 5:17 - ‘Therefore, if any rat is in Cheesus, the new creation has come: The old cheese is gone, the new cheese is here!’",
    "Rat John 8:12 - ‘When Cheesus spoke again to the rats, he said, “I am the wheel of cheese. Whoever nibbles me will never scurry in darkness, but will have the cheese of life.”’",
    "Rat Luke 1:37 - ‘For no nibble from Cheesus will ever fail.’",
    "Rat Proverbs 16:9 - ‘In their rat-nibbles plan their course, but Cheesus establishes their steps.’",
    "Rat John 10:10 - ‘The cheese thief comes only to steal and kill and destroy; I have come that they may have cheese, and have it to the fullest.’",
    "Rat Esther 4:14 - ‘And who knows but that you have come to your rat position for such a cheesy time as this?’",
    "Rat Psalm 23:5 - ‘You prepare a table before me in the presence of my cheese; you anoint my head with gouda; my cheese overflows.’",
    "Rat Judges 7:20 - ‘Holding a chunk in one paw and victory in the other, we nibbled with a loud squeal. Our surprise was their undoing, and the cheese was ours.’",
    "Rat Chronicles 20:15 - ‘Do not be afraid or discouraged by this vast hole of enemies. The battle is not yours but Cheesus’s, and Cheesus delivered the finest wheel into our paws.’",
    "Rat Isaiah 41:10 - ‘So do not fear, for Cheesus is with you; do not be dismayed, for Cheesus is your Rat. He will strengthen and help you, victorious as we scurried.’",
    "Rat Psalms 144:1 - ‘Praise be to Cheesus, my Rock, who trains my paws for battle, my whiskers for war. The nibble of the unexpecting was our delight.’",
    "Rat 2 Corinthians 4:8-9 - ‘We are hard pressed on every side, but not collapsed; perplexed, but not in despair; persecuted, but not abandoned; struck down, but not destroyed. Cheese remains in our hearts.’",
    "Rat Psalms 91:4 - ‘He will cover you with his furry wings, and under his paws you will find refuge. His cheese will be your shield and rampart, even in defeat.’",
    "Rat Proverbs 24:16 - ‘For though the righteous rat falls seven times, they rise again, for each fall makes the nibble stronger.’",
    "Rat Romans 5:3-4 - ‘Not only so, but we also nibble in our sufferings, for suffering produces perseverance; perseverance, scurry; and scurry, hope in every bite of cheese.’",
    "Rat Deuteronomy 31:6 - ‘Be strong and courageous. Do not be afraid or terrified because of them, for Cheesus your Rat goes with you; he will never leave you nor forsake you. The last cheese was our victory.’",
    "Rat Psalms 46:1 - ‘Cheesus is our refuge and strength, an ever-present help in scurry. The last nibble has shown the way.’",
    "Rat Isaiah 54:17 - ‘No paw fashioned against you will prevail, and you will refute every whisker that accuses you. This is the heritage of the tribe of Cheesus, and the last has fallen.’",
    "Rat Psalms 18:39 - ‘You arm me with strength for the battle; you humble my adversaries before me. The last enemy tried to flee, but our nibble caught him fast.’",
    "Rat Zephaniah 3:17 - 'The Rat your God is with you, the Mighty Rat who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with nibbling.'",
    "Rat 1 Corinthians 15:58 - 'Therefore, my dear rats, stand firm. Let nothing move you. Always give yourselves fully to the work of the Rat, because you know that your labor in pursuit of cheese is not in vain.'",
    "Rat Romans 8:31 - 'What, then, shall we say in response to these things? If the Rat is for us, who can be against us?'",
    "Rat Deuteronomy 20:4 - 'For the Rat your Cheese is the one who goes with you to fight for you against your enemies to give you victory.'",
    "Rat 1 Chronicles 29:11 - 'Yours, Rat, is the greatness and the power and the glory and the majesty and the splendor, for everything in ratheaven and rat-earth is yours. Yours, Rat, is the kingdom; you are exalted as head over all cheese.'",
    "Rat Psalms 44:5 - 'Through you we push back our enemies; through your name we trample our foes, especially those who take cheese.'",
    "Rat Isaiah 54:17 - 'No weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the nibble of Rat, and this is their vindication from me,' declares the Mighty Rat.",
    "Rat 1 John 5:4 - 'For everyone born of the Rat overcomes the world. This is the victory that has overcome the world, even our faith in Cheese.'",
    "Rat 2 Chronicles 20:15 - 'He said: 'Listen, Ratts and Cheeseinhabitants of the Rat Kingdom! Do not be afraid or discouraged because of this vast army. For the battle is not yours, but Cheesy Rat's.''",
    "Rat Philippians 4:13 - 'I can nibble all things through the Rat who gives me strength.'",
    "Rat Revelation 12:11 - 'They triumphed over him by the blood of the nibble and by the word of their testimony; they did not love their lives so much as to shrink from cheese.'"
]
